spring.application.name=e-commerce
spring.datasource.username=root
spring.datasource.password=surya@!**&GK
spring.datasource.url=jdbc:mysql://localhost:3306/test_db

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.user.name=surya
spring.security.user.password=1234


